CREATE SMALLFILE TABLESPACE AKHIL 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE SMALLFILE TABLESPACE SYSAUX 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE SMALLFILE TABLESPACE SYSTEM 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT MANUAL 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE SMALLFILE TEMPORARY TABLESPACE TEMP 
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1048576;

CREATE SMALLFILE UNDO TABLESPACE UNDOTBS1 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
    RETENTION NOGUARANTEE;

CREATE SMALLFILE TABLESPACE USERS 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLE ADDRESS 
(
  ADDRESS_ID NUMBER(18, 0) NOT NULL 
, BUILDING_INFO VARCHAR2(1000 BYTE) NOT NULL 
, STREET_NAME VARCHAR2(20 BYTE) 
, ZIPCODE NUMBER(18, 0) NOT NULL 
, CONSTRAINT ADDRESS_PK PRIMARY KEY 
  (
    ADDRESS_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ADDRESS_PK ON ADDRESS (ADDRESS_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE APPOINTMENTS 
(
  APPOINTMENT_ID NUMBER NOT NULL 
, APPOINTMENT_NAME VARCHAR2(255 CHAR) NOT NULL 
, APPOINTMENT_START_TIME DATE NOT NULL 
, APPOINTMENT_END_TIME DATE NOT NULL 
, DESCRIPTION VARCHAR2(1000 CHAR) DEFAULT 'Not available' 
, APPOINTMENT_LOCATION NUMBER(18, 0) NOT NULL 
, CONSTRAINT APPOINTMENTS_PK PRIMARY KEY 
  (
    APPOINTMENT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX APPOINTMENTS_PK ON APPOINTMENTS (APPOINTMENT_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE APPOINTMENT_CUSTOMER_LINK 
(
  APPOINTMENT_ID NUMBER NOT NULL 
, CUSTOMER_ID NUMBER NOT NULL 
, CONSTRAINT APPOINTMENT_CUSTOMER_LINK_PK PRIMARY KEY 
  (
    APPOINTMENT_ID 
  , CUSTOMER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX APPOINTMENT_CUSTOMER_LINK_PK ON APPOINTMENT_CUSTOMER_LINK (APPOINTMENT_ID ASC, CUSTOMER_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE APPOINTMENT_USER_LINK 
(
  APPOINTMENT_ID NUMBER NOT NULL 
, USER_ID NUMBER NOT NULL 
, CONSTRAINT APPOINTMENT_USER_LINK_PK PRIMARY KEY 
  (
    APPOINTMENT_ID 
  , USER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX APPOINTMENT_USER_LINK_PK ON APPOINTMENT_USER_LINK (APPOINTMENT_ID ASC, USER_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CATEGORY_TABLE 
(
  CATEGORY_ID NUMBER(18, 0) NOT NULL 
, CATEGORY_NAME VARCHAR2(255 CHAR) NOT NULL 
, CATEGORY_DESCRIPTION VARCHAR2(1000 CHAR) DEFAULT 'Not Available' 
, CONSTRAINT CATEGORY_PK PRIMARY KEY 
  (
    CATEGORY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CATEGORY_PK ON CATEGORY_TABLE (CATEGORY_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CONTACTS 
(
  CONTACT_ID NUMBER NOT NULL 
, CONTACT_NAME VARCHAR2(30 CHAR) NOT NULL 
, GENDER NUMBER(18, 0) 
, WORK_NUMBER VARCHAR2(20 CHAR) NOT NULL 
, EMAIL VARCHAR2(30 CHAR) NOT NULL 
, TITLE NUMBER(18, 0) 
, DEPARTMENT_NAME VARCHAR2(30 CHAR) 
, ADDRESS VARCHAR2(100 CHAR) 
, MOBILE_NUMBER VARCHAR2(30 CHAR) NOT NULL 
, BUYING_ROLE NUMBER(18, 0) 
, INFLUENCE_LEVEL NUMBER(18, 0) 
, CONSTRAINT CONTACTS_PK PRIMARY KEY 
  (
    CONTACT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CONTACTS_PK ON CONTACTS (CONTACT_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CONTACT_INTERACTION_LINK 
(
  INTERACTION_ID NUMBER NOT NULL 
, CONTACT_ID NUMBER NOT NULL 
, CONSTRAINT CONTACT_INTERACTION_LINK_PK PRIMARY KEY 
  (
    INTERACTION_ID 
  , CONTACT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CONTACT_INTERACTION_LINK_PK ON CONTACT_INTERACTION_LINK (INTERACTION_ID ASC, CONTACT_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CONTACT_NOTES_LINK 
(
  NOTE_ID NUMBER NOT NULL 
, CONTACT_ID NUMBER NOT NULL 
, CONSTRAINT CONTACT_NOTES_PK PRIMARY KEY 
  (
    NOTE_ID 
  , CONTACT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CONTACT_NOTES_PK ON CONTACT_NOTES_LINK (NOTE_ID ASC, CONTACT_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CONTACT_TASK_LINK 
(
  CONTACT_ID NUMBER NOT NULL 
, TASK_ID NUMBER NOT NULL 
, CONSTRAINT CONTACT_TASK_LINK_PK PRIMARY KEY 
  (
    CONTACT_ID 
  , TASK_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CONTACT_TASK_LINK_PK ON CONTACT_TASK_LINK (CONTACT_ID ASC, TASK_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CONTRACTS 
(
  CONTRACT_ID NUMBER NOT NULL 
, ACCOUNT_ID NUMBER NOT NULL 
, CONTRACT_START_DATE DATE NOT NULL 
, CONTRACT_END_DATE DATE 
, CONTRACT_STATE NUMBER NOT NULL 
, SALES_METHOD NUMBER 
, SALES_CHANNEL NUMBER 
, REVENUE NUMBER DEFAULT 0 
, USER_IN_CHARGE NUMBER NOT NULL 
, CONSTRAINT CONTRACT_PK PRIMARY KEY 
  (
    CONTRACT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CONTRACT_PK ON CONTRACTS (CONTRACT_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CONTRACT_REVENUE_ITEMS 
(
  CONTRACT_ID NUMBER NOT NULL 
, PROD_CODE NUMBER NOT NULL 
, PRICE NUMBER NOT NULL 
, QUANTITY NUMBER NOT NULL 
, CONSTRAINT CONTRACT_REVENUE_ITEMS_PK PRIMARY KEY 
  (
    CONTRACT_ID 
  , PROD_CODE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CONTRACT_REVENUE_ITEMS_PK ON CONTRACT_REVENUE_ITEMS (CONTRACT_ID ASC, PROD_CODE ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CUSTOMER_ACCOUNTS 
(
  ACCOUNT_ID NUMBER(18, 0) NOT NULL 
, ACCOUNT_NAME VARCHAR2(255 CHAR) NOT NULL 
, ACCOUNT_ADDRESS NUMBER(18, 0) NOT NULL 
, ACCOUNT_URL VARCHAR2(1000 CHAR) NOT NULL 
, PARENT_ACCOUNT_ID NUMBER 
, CEO VARCHAR2(255 CHAR) NOT NULL 
, EMP_COUNT NUMBER(18, 0) DEFAULT 0 NOT NULL 
, PRIMARY_ADDRESS NUMBER(18, 0) NOT NULL 
, SHIPPING_ADDRESS NUMBER(18, 0) 
, CONSTRAINT CUSTOMER_ACCOUNT_PK PRIMARY KEY 
  (
    ACCOUNT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CUSTOMER_ACCOUNT_PK ON CUSTOMER_ACCOUNTS (ACCOUNT_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CUST_ACCOUNT_TASK_LINK 
(
  TASK_ID NUMBER NOT NULL 
, CUST_ID NUMBER NOT NULL 
, CONSTRAINT CUST_ACCOUNT_TASK_PK PRIMARY KEY 
  (
    TASK_ID 
  , CUST_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CUST_ACCOUNT_TASK_PK ON CUST_ACCOUNT_TASK_LINK (TASK_ID ASC, CUST_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CUST_CONTACT_LK 
(
  ACC_ID NUMBER NOT NULL 
, CONTACT_ID NUMBER NOT NULL 
, PRIMARY NUMBER NOT NULL 
, CONSTRAINT CUST_CONTACT_LK_PK PRIMARY KEY 
  (
    ACC_ID 
  , CONTACT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CUST_CONTACT_LK_PK ON CUST_CONTACT_LK (ACC_ID ASC, CONTACT_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE CUST_NOTES_LINK 
(
  NOTE_ID NUMBER NOT NULL 
, CUST_ID NUMBER NOT NULL 
, CONSTRAINT CUST_NOTES_PK PRIMARY KEY 
  (
    NOTE_ID 
  , CUST_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CUST_NOTES_PK ON CUST_NOTES_LINK (NOTE_ID ASC, CUST_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE INTERACTIONS 
(
  ID NUMBER NOT NULL 
, TYPE VARCHAR2(20 BYTE) NOT NULL 
, END_DATE DATE 
, START_DATE DATE 
, DESCRIPTION VARCHAR2(100 BYTE) 
, RESOLUTION VARCHAR2(100 BYTE) 
, CONSTRAINT INTERACTIONS_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX INTERACTIONS_PK ON INTERACTIONS (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE LOCATION 
(
  ZIP_CODE NUMBER(18, 0) NOT NULL 
, CITY VARCHAR2(255 BYTE) NOT NULL 
, STATE VARCHAR2(255 BYTE) NOT NULL 
, COUNTRY VARCHAR2(255 BYTE) NOT NULL 
, CONSTRAINT LOCATION_PK PRIMARY KEY 
  (
    ZIP_CODE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LOCATION_PK ON LOCATION (ZIP_CODE ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE LOOKUP 
(
  ID NUMBER NOT NULL 
, VALUE VARCHAR2(255 BYTE) NOT NULL 
, TYPE VARCHAR2(255 BYTE) NOT NULL 
, CONSTRAINT LOOKUP_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LOOKUP_PK ON LOOKUP (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE NOTES 
(
  NOTE_ID NUMBER(18, 0) NOT NULL 
, NOTE_DATE DATE NOT NULL 
, NOTE_TITLE VARCHAR2(255 CHAR) NOT NULL 
, NOTE_CONTENT VARCHAR2(1000 CHAR) 
, NOTE_CREATOR_ID NUMBER(18, 0) NOT NULL 
, CONSTRAINT NOTES_PK PRIMARY KEY 
  (
    NOTE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX NOTES_PK ON NOTES (NOTE_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE OPPORTUNITY 
(
  ID NUMBER(18, 0) NOT NULL 
, ACC_ID NUMBER(18, 0) NOT NULL 
, OPPORTUNITY_WIN_PROB NUMBER(18, 0) 
, OPPORTUNITY_CLOSE_DATE DATE NOT NULL 
, PRIMARY_CONTACT_ID NUMBER(18, 0) NOT NULL 
, SALES_STAGE VARCHAR2(255 CHAR) 
, SALES_METHOD VARCHAR2(255 CHAR) 
, CHANNEL VARCHAR2(255 CHAR) 
, REVENUE NUMBER(18, 2) 
, BEST_CASE_REVENUE NUMBER(18, 2) 
, WORST_CASE_REVENUE NUMBER(18, 2) 
, BUDGET_AMOUNT NUMBER(18, 2) 
, ESTIMATED_DURATION NUMBER(18, 0) 
, RISK_LEVEL VARCHAR2(255 CHAR) 
, DECISION_LEVEL VARCHAR2(255 CHAR) 
, CREATOR_ID NUMBER(18, 0) 
, CONSTRAINT OPPORTUNITY_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OPPORTUNITY_PK ON OPPORTUNITY (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE OPPORTUNITY_INTERACTION_LINK 
(
  OPPERTUNITY_ID NUMBER NOT NULL 
, INTERACTION_ID NUMBER NOT NULL 
, CONSTRAINT OPPORTUNITY_INTERACTION_LI_PK PRIMARY KEY 
  (
    OPPERTUNITY_ID 
  , INTERACTION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OPPERTUNITY_INTERACTION_LI_PK ON OPPORTUNITY_INTERACTION_LINK (OPPERTUNITY_ID ASC, INTERACTION_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE OPPORTUNITY_NOTE_LINK 
(
  OPPORTUNITY_ID NUMBER NOT NULL 
, NOTE_ID NUMBER NOT NULL 
, CONSTRAINT OPPERTUNITY_NOTE_PK PRIMARY KEY 
  (
    OPPORTUNITY_ID 
  , NOTE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OPPERTUNITY_NOTE_PK ON OPPORTUNITY_NOTE_LINK (OPPORTUNITY_ID ASC, NOTE_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE OPPORTUNITY_TASK_LINK 
(
  OPPORTUNITY_ID NUMBER NOT NULL 
, TASK_ID NUMBER NOT NULL 
, CONSTRAINT OPPORTUNITY_TASK_LINK_PK PRIMARY KEY 
  (
    OPPORTUNITY_ID 
  , TASK_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OPPORTUNITY_TASK_LINK_PK ON OPPORTUNITY_TASK_LINK (OPPORTUNITY_ID ASC, TASK_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE PRODUCTS 
(
  PRODUCT_CODE NUMBER NOT NULL 
, PRODUCT_NAME VARCHAR2(255 CHAR) NOT NULL 
, PRODUCT_DESCRIPTION VARCHAR2(1000 CHAR) 
, PRODUCT_PRICE NUMBER(10, 2) NOT NULL 
, PRODUCT_CATEGORY NUMBER 
, CONSTRAINT PRODUCTS_PK PRIMARY KEY 
  (
    PRODUCT_CODE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PRODUCTS_PK ON PRODUCTS (PRODUCT_CODE ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE REVENUE_ITEMS 
(
  OPPURTUNITY_ID NUMBER NOT NULL 
, PRODUCT_ID NUMBER NOT NULL 
, WIN_PROBABILITY NUMBER(5, 2) 
, BEST_CASE_REVENUE NUMBER(10, 2) 
, WORSE_CASE_REVENUE NUMBER(10, 2) 
, QUANTITY NUMBER 
, SETTLED_PRICE NUMBER(10, 2) 
, CONSTRAINT REVENUE_ITEMS_PK PRIMARY KEY 
  (
    OPPURTUNITY_ID 
  , PRODUCT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX REVENUE_ITEMS_PK ON REVENUE_ITEMS (OPPURTUNITY_ID ASC, PRODUCT_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE ROLES_TABLE 
(
  ID NUMBER NOT NULL 
, ROLE_NAME VARCHAR2(255 CHAR) NOT NULL 
, ROLE_DESCRIPTION VARCHAR2(1000 CHAR) DEFAULT 'Not Available' 
, START_DATE DATE NOT NULL 
, END_DATE DATE 
, CONSTRAINT ROLES_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ROLES_PK ON ROLES_TABLE (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE SALES_TEAMS 
(
  TEAM_ID NUMBER(18, 0) NOT NULL 
, MANAGER_ID NUMBER(18, 0) NOT NULL 
, TEAM_NAME VARCHAR2(255 CHAR) NOT NULL 
, CONSTRAINT SALES_TEAMS_PK PRIMARY KEY 
  (
    TEAM_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SALES_TEAMS_PK ON SALES_TEAMS (TEAM_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE SALES_TEAM_OPPERTUNITY_LINK 
(
  OPPORTUNITY_ID NUMBER NOT NULL 
, SALES_ID NUMBER NOT NULL 
, CONSTRAINT SALES_TEAM_OPPERTUNITY_LIN_PK PRIMARY KEY 
  (
    OPPORTUNITY_ID 
  , SALES_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SALES_TEAM_OPPERTUNITY_LIN_PK ON SALES_TEAM_OPPERTUNITY_LINK (OPPORTUNITY_ID ASC, SALES_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE TASK 
(
  TASK_ID NUMBER(18, 0) NOT NULL 
, TASK_NAME VARCHAR2(255 CHAR) NOT NULL 
, DUE_DATE DATE NOT NULL 
, TASK_START_DATE DATE 
, TASK_PRIORITY VARCHAR2(255 CHAR) NOT NULL 
, TASK_DESCRIPTION VARCHAR2(1000 CHAR) 
, ASSIGNEE_ID NUMBER(18, 0) 
, TASK_COMPLETION NUMBER(18, 2) DEFAULT 0 NOT NULL 
, TASK_OWNER_ID NUMBER(18, 0) NOT NULL 
, CONSTRAINT TASK_PK PRIMARY KEY 
  (
    TASK_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TASK_PK ON TASK (TASK_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE USERS 
(
  USER_ID NUMBER(18, 0) NOT NULL 
, U_NAME VARCHAR2(255 CHAR) NOT NULL 
, U_PASSWORD VARCHAR2(255 CHAR) NOT NULL 
, USER_REF_ID VARCHAR2(255 CHAR) NOT NULL 
, FIRST_NAME VARCHAR2(255 CHAR) NOT NULL 
, LAST_NAME VARCHAR2(255 CHAR) NOT NULL 
, MIDDLE_NAME VARCHAR2(255 CHAR) 
, GENDER NUMBER(18, 0) 
, SALES_TEAM_ID NUMBER(18, 0) 
, START_DATE DATE 
, END_DATE DATE 
, ADDRESS_ID NUMBER(18, 0) 
, CONSTRAINT USERACCOUNTS_PK PRIMARY KEY 
  (
    USER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USERACCOUNTS_PK ON USERS (USER_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE USER_INTERACTION_LINK 
(
  INTERACTION_ID NUMBER NOT NULL 
, USER_ID NUMBER NOT NULL 
, CONSTRAINT USER_INTERACTION_LINK_PK PRIMARY KEY 
  (
    USER_ID 
  , INTERACTION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USER_INTERACTION_LINK_PK ON USER_INTERACTION_LINK (USER_ID ASC, INTERACTION_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE USER_ROLE_LINK 
(
  ROLE_ID NUMBER(18, 0) NOT NULL 
, USER_ID NUMBER(18, 0) NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE ADDRESS
ADD CONSTRAINT ADDRESS_FK1 FOREIGN KEY
(
  ZIPCODE 
)
REFERENCES LOCATION
(
  ZIP_CODE 
)
ENABLE;

ALTER TABLE APPOINTMENT_CUSTOMER_LINK
ADD CONSTRAINT APPOINTMENT_FK FOREIGN KEY
(
  APPOINTMENT_ID 
)
REFERENCES APPOINTMENTS
(
  APPOINTMENT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE APPOINTMENT_CUSTOMER_LINK
ADD CONSTRAINT CUSTOMER_FK FOREIGN KEY
(
  CUSTOMER_ID 
)
REFERENCES CUSTOMER_ACCOUNTS
(
  ACCOUNT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE APPOINTMENT_USER_LINK
ADD CONSTRAINT APPOINTMENT_FK2 FOREIGN KEY
(
  APPOINTMENT_ID 
)
REFERENCES APPOINTMENTS
(
  APPOINTMENT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE APPOINTMENT_USER_LINK
ADD CONSTRAINT USER_FK2 FOREIGN KEY
(
  USER_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CONTACTS
ADD CONSTRAINT CONTACTS_FK1 FOREIGN KEY
(
  BUYING_ROLE 
)
REFERENCES LOOKUP
(
  ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE CONTACTS
ADD CONSTRAINT CONTACTS_FK2 FOREIGN KEY
(
  INFLUENCE_LEVEL 
)
REFERENCES LOOKUP
(
  ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE CONTACTS
ADD CONSTRAINT CONTACTS_FK3 FOREIGN KEY
(
  TITLE 
)
REFERENCES LOOKUP
(
  ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE CONTACTS
ADD CONSTRAINT CONTACTS_FK4 FOREIGN KEY
(
  GENDER 
)
REFERENCES LOOKUP
(
  ID 
)
ENABLE;

ALTER TABLE CONTACT_INTERACTION_LINK
ADD CONSTRAINT CONTACT_FK FOREIGN KEY
(
  CONTACT_ID 
)
REFERENCES CONTACTS
(
  CONTACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CONTACT_INTERACTION_LINK
ADD CONSTRAINT INTERACTION_FK FOREIGN KEY
(
  INTERACTION_ID 
)
REFERENCES INTERACTIONS
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CONTACT_NOTES_LINK
ADD CONSTRAINT CONTACT_NOTES_FK1 FOREIGN KEY
(
  CONTACT_ID 
)
REFERENCES CONTACTS
(
  CONTACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CONTACT_NOTES_LINK
ADD CONSTRAINT CONTACT_NOTES_FK2 FOREIGN KEY
(
  NOTE_ID 
)
REFERENCES NOTES
(
  NOTE_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CONTACT_TASK_LINK
ADD CONSTRAINT CONTACT_TASK_LINK_FK1 FOREIGN KEY
(
  TASK_ID 
)
REFERENCES TASK
(
  TASK_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CONTACT_TASK_LINK
ADD CONSTRAINT CONTACT_TASK_LINK_FK2 FOREIGN KEY
(
  CONTACT_ID 
)
REFERENCES CONTACTS
(
  CONTACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CONTRACTS
ADD CONSTRAINT CONTRACTS_FK1 FOREIGN KEY
(
  CONTRACT_STATE 
)
REFERENCES LOOKUP
(
  ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE CONTRACTS
ADD CONSTRAINT CONTRACTS_FK2 FOREIGN KEY
(
  SALES_METHOD 
)
REFERENCES LOOKUP
(
  ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE CONTRACTS
ADD CONSTRAINT CONTRACTS_FK3 FOREIGN KEY
(
  SALES_CHANNEL 
)
REFERENCES LOOKUP
(
  ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE CONTRACTS
ADD CONSTRAINT CONTRACT_CUSTOMER_FK FOREIGN KEY
(
  ACCOUNT_ID 
)
REFERENCES CUSTOMER_ACCOUNTS
(
  ACCOUNT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CONTRACTS
ADD CONSTRAINT CONTRACT_USER_FK FOREIGN KEY
(
  USER_IN_CHARGE 
)
REFERENCES USERS
(
  USER_ID 
)
ENABLE;

ALTER TABLE CONTRACT_REVENUE_ITEMS
ADD CONSTRAINT CONTRACT_REVENUE_ITEMS_FK1 FOREIGN KEY
(
  CONTRACT_ID 
)
REFERENCES CONTRACTS
(
  CONTRACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CONTRACT_REVENUE_ITEMS
ADD CONSTRAINT CONTRACT_REVENUE_ITEMS_FK2 FOREIGN KEY
(
  PROD_CODE 
)
REFERENCES PRODUCTS
(
  PRODUCT_CODE 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CUSTOMER_ACCOUNTS
ADD CONSTRAINT CUSTOMER_ACCOUNTS_FK1 FOREIGN KEY
(
  PARENT_ACCOUNT_ID 
)
REFERENCES CUSTOMER_ACCOUNTS
(
  ACCOUNT_ID 
)
ENABLE;

ALTER TABLE CUSTOMER_ACCOUNTS
ADD CONSTRAINT CUSTOMER_ACCOUNTS_FK2 FOREIGN KEY
(
  PRIMARY_ADDRESS 
)
REFERENCES ADDRESS
(
  ADDRESS_ID 
)
ENABLE;

ALTER TABLE CUSTOMER_ACCOUNTS
ADD CONSTRAINT CUSTOMER_ACCOUNTS_FK3 FOREIGN KEY
(
  SHIPPING_ADDRESS 
)
REFERENCES ADDRESS
(
  ADDRESS_ID 
)
ENABLE;

ALTER TABLE CUST_ACCOUNT_TASK_LINK
ADD CONSTRAINT CUST_ACCOUNT_TASK_FK1 FOREIGN KEY
(
  TASK_ID 
)
REFERENCES TASK
(
  TASK_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CUST_ACCOUNT_TASK_LINK
ADD CONSTRAINT CUST_ACCOUNT_TASK_FK2 FOREIGN KEY
(
  CUST_ID 
)
REFERENCES CUSTOMER_ACCOUNTS
(
  ACCOUNT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CUST_CONTACT_LK
ADD CONSTRAINT CUST_CONTACT_LK_FK1 FOREIGN KEY
(
  ACC_ID 
)
REFERENCES CUSTOMER_ACCOUNTS
(
  ACCOUNT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CUST_CONTACT_LK
ADD CONSTRAINT CUST_CONTACT_LK_FK2 FOREIGN KEY
(
  CONTACT_ID 
)
REFERENCES CONTACTS
(
  CONTACT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CUST_NOTES_LINK
ADD CONSTRAINT CUST_NOTES_FK1 FOREIGN KEY
(
  NOTE_ID 
)
REFERENCES NOTES
(
  NOTE_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CUST_NOTES_LINK
ADD CONSTRAINT CUST_NOTES_FK2 FOREIGN KEY
(
  CUST_ID 
)
REFERENCES CUSTOMER_ACCOUNTS
(
  ACCOUNT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE NOTES
ADD CONSTRAINT NOTES_FK1 FOREIGN KEY
(
  NOTE_CREATOR_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT CREATOR_ID_FK FOREIGN KEY
(
  CREATOR_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT CUST_ACCOUNT_ID_FK1 FOREIGN KEY
(
  ACC_ID 
)
REFERENCES CUSTOMER_ACCOUNTS
(
  ACCOUNT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT PRIMARY_CONTACT_FK1 FOREIGN KEY
(
  PRIMARY_CONTACT_ID 
)
REFERENCES CONTACTS
(
  CONTACT_ID 
)
ENABLE;

ALTER TABLE OPPORTUNITY_INTERACTION_LINK
ADD CONSTRAINT OPPERTUNITY_INTERACTION_L_FK1 FOREIGN KEY
(
  INTERACTION_ID 
)
REFERENCES INTERACTIONS
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OPPORTUNITY_INTERACTION_LINK
ADD CONSTRAINT OPPERTUNITY_INTERACTION_L_FK2 FOREIGN KEY
(
  OPPERTUNITY_ID 
)
REFERENCES OPPORTUNITY
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OPPORTUNITY_NOTE_LINK
ADD CONSTRAINT OPPERTUNITY_NOTE_FK1 FOREIGN KEY
(
  OPPORTUNITY_ID 
)
REFERENCES OPPORTUNITY
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OPPORTUNITY_NOTE_LINK
ADD CONSTRAINT OPPERTUNITY_NOTE_FK2 FOREIGN KEY
(
  NOTE_ID 
)
REFERENCES NOTES
(
  NOTE_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OPPORTUNITY_TASK_LINK
ADD CONSTRAINT OPPORTUNITY_TASK_LINK_FK1 FOREIGN KEY
(
  TASK_ID 
)
REFERENCES TASK
(
  TASK_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OPPORTUNITY_TASK_LINK
ADD CONSTRAINT OPPORTUNITY_TASK_LINK_FK2 FOREIGN KEY
(
  OPPORTUNITY_ID 
)
REFERENCES OPPORTUNITY
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE PRODUCTS
ADD CONSTRAINT PRODUCTS_FK1 FOREIGN KEY
(
  PRODUCT_CATEGORY 
)
REFERENCES CATEGORY_TABLE
(
  CATEGORY_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE REVENUE_ITEMS
ADD CONSTRAINT REVENUE_ITEMS_FK1 FOREIGN KEY
(
  OPPURTUNITY_ID 
)
REFERENCES OPPORTUNITY
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE REVENUE_ITEMS
ADD CONSTRAINT REVENUE_ITEMS_FK2 FOREIGN KEY
(
  PRODUCT_ID 
)
REFERENCES PRODUCTS
(
  PRODUCT_CODE 
)
ENABLE;

ALTER TABLE SALES_TEAMS
ADD CONSTRAINT MANAGER_SALES_FK FOREIGN KEY
(
  MANAGER_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE SALES_TEAM_OPPERTUNITY_LINK
ADD CONSTRAINT SALES_TEAM_OPPERTUNITY_LI_FK1 FOREIGN KEY
(
  SALES_ID 
)
REFERENCES SALES_TEAMS
(
  TEAM_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE SALES_TEAM_OPPERTUNITY_LINK
ADD CONSTRAINT SALES_TEAM_OPPERTUNITY_LI_FK2 FOREIGN KEY
(
  OPPORTUNITY_ID 
)
REFERENCES OPPORTUNITY
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE TASK
ADD CONSTRAINT TASK_FK1 FOREIGN KEY
(
  ASSIGNEE_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE TASK
ADD CONSTRAINT TASK_FK2 FOREIGN KEY
(
  TASK_OWNER_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE USERS
ADD CONSTRAINT USERS_FK1 FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES ADDRESS
(
  ADDRESS_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE USERS
ADD CONSTRAINT USER_SALESTEAM_FK FOREIGN KEY
(
  SALES_TEAM_ID 
)
REFERENCES SALES_TEAMS
(
  TEAM_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE USER_INTERACTION_LINK
ADD CONSTRAINT INTERACTION_USER_FK FOREIGN KEY
(
  INTERACTION_ID 
)
REFERENCES INTERACTIONS
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE USER_INTERACTION_LINK
ADD CONSTRAINT USER_FK FOREIGN KEY
(
  USER_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE USER_ROLE_LINK
ADD CONSTRAINT USER_ROLE_LINK_FK1 FOREIGN KEY
(
  USER_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE USER_ROLE_LINK
ADD CONSTRAINT USER_ROLE_LINK_FK2 FOREIGN KEY
(
  ROLE_ID 
)
REFERENCES ROLES_TABLE
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CATEGORY_TABLE
ADD CONSTRAINT CATEGORY_CHK1 CHECK 
(LENGTH(CATEGORY_NAME) > 3)
ENABLE;

ALTER TABLE CONTACTS
ADD CONSTRAINT CONTACTS_CHK1 CHECK 
(LENGTH(CONTACT_NAME) > 2)
ENABLE;

ALTER TABLE CONTACTS
ADD CONSTRAINT CONTACTS_CHK2 CHECK 
(LENGTH(MOBILE_NUMBER) > 10)
ENABLE;

ALTER TABLE CONTRACTS
ADD CONSTRAINT CONTRACTS_CHK1 CHECK 
(CONTRACT_START_DATE < CONTRACT_END_DATE)
ENABLE;

ALTER TABLE CONTRACTS
ADD CONSTRAINT CONTRACTS_CHK3 CHECK 
(REVENUE>=0)
ENABLE;

ALTER TABLE CONTRACT_REVENUE_ITEMS
ADD CONSTRAINT CONTRACT_REVENUE_ITEMS_CHK1 CHECK 
(PRICE >= 0)
ENABLE;

ALTER TABLE CONTRACT_REVENUE_ITEMS
ADD CONSTRAINT CONTRACT_REVENUE_ITEMS_CHK2 CHECK 
(QUANTITY >=0)
ENABLE;

ALTER TABLE CUSTOMER_ACCOUNTS
ADD CONSTRAINT CUSTOMER_ACCOUNTS_CHK1 CHECK 
(LENGTH(ACCOUNT_NAME) > 2)
ENABLE;

ALTER TABLE CUST_CONTACT_LK
ADD CONSTRAINT CUST_CONTACT_LK_CHK1 CHECK 
(PRIMARY IN (0,1))
ENABLE;

ALTER TABLE INTERACTIONS
ADD CONSTRAINT INTERACTIONS_CHK1 CHECK 
(TYPE IN ( 'CONFERENCE' , 'EMAIL' , 'PHONE' , 'FAX' , 'CHAT' , 'MEETING' , 'WEBCONFERENCE' , 'OTHERS' ))
ENABLE;

ALTER TABLE INTERACTIONS
ADD CONSTRAINT INTERACTIONS_CHK2 CHECK 
(START_DATE < END_DATE)
ENABLE;

ALTER TABLE INTERACTIONS
ADD CONSTRAINT INTERACTIONS_CHK3 CHECK 
(LENGTH(DESCRIPTION) BETWEEN 1 AND 100)
ENABLE;

ALTER TABLE INTERACTIONS
ADD CONSTRAINT INTERACTIONS_CHK4 CHECK 
(LENGTH(RESOLUTION) BETWEEN 1 AND 100)
ENABLE;

ALTER TABLE NOTES
ADD CONSTRAINT NOTES_CHK1 CHECK 
(LENGTH(NOTE_TITLE) BETWEEN 1 AND 50)
ENABLE;

ALTER TABLE NOTES
ADD CONSTRAINT NOTES_CHK2 CHECK 
(LENGTH(NOTE_CONTENT) >= 0 AND LENGTH(NOTE_CONTENT) <= 499)
ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT OPPORTUNITY_CHK1 CHECK 
(OPPORTUNITY_WIN_PROB >= 0 AND OPPORTUNITY_WIN_PROB <= 100)
ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT OPPORTUNITY_CHK2 CHECK 
(SALES_STAGE IN ('QUALIFICATION', 'OPPERTUNITY', 'BUILDING VISION' , 'PRESENTATION', 'AGREEMENT' , 'NEGOTIATION','CLOSED','FAILED'))
ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT OPPORTUNITY_CHK3 CHECK 
(SALES_METHOD IN ('STANDARD','CUSTOM'))
ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT OPPORTUNITY_CHK4 CHECK 
(CHANNEL IN ('DIRECT','INDIRECT'))
ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT OPPORTUNITY_CHK5 CHECK 
(REVENUE>=0)
ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT OPPORTUNITY_CHK6 CHECK 
(BEST_CASE_REVENUE >= 0 AND WORST_CASE_REVENUE >= 0 AND BUDGET_AMOUNT >= 0)
ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT OPPORTUNITY_CHK7 CHECK 
(RISK_LEVEL IN ('HIGH','MEDIUM','LOW'))
ENABLE;

ALTER TABLE OPPORTUNITY
ADD CONSTRAINT OPPORTUNITY_CHK8 CHECK 
(DECISION_LEVEL IN ('HIGH','MEDIUM','LOW'))
ENABLE;

ALTER TABLE PRODUCTS
ADD CONSTRAINT PRODUCTS_CHK1 CHECK 
(PRODUCT_PRICE >= 0)
ENABLE;

ALTER TABLE PRODUCTS
ADD CONSTRAINT PRODUCTS_CHK2 CHECK 
(LENGTH(PRODUCT_NAME) BETWEEN 1 AND 255)
ENABLE;

ALTER TABLE PRODUCTS
ADD CONSTRAINT PRODUCTS_CHK3 CHECK 
(LENGTH(PRODUCT_DESCRIPTION) BETWEEN 0 AND 1000)
ENABLE;

ALTER TABLE REVENUE_ITEMS
ADD CONSTRAINT REVENUE_ITEMS_CHK1 CHECK 
(WIN_PROBABILITY >= 0 AND WIN_PROBABILITY <= 100)
ENABLE;

ALTER TABLE REVENUE_ITEMS
ADD CONSTRAINT REVENUE_ITEMS_CHK2 CHECK 
(BEST_CASE_REVENUE>=0 AND BEST_CASE_REVENUE <=100)
ENABLE;

ALTER TABLE REVENUE_ITEMS
ADD CONSTRAINT REVENUE_ITEMS_CHK3 CHECK 
(WORSE_CASE_REVENUE>=0 AND WORSE_CASE_REVENUE <=100)
ENABLE;

ALTER TABLE REVENUE_ITEMS
ADD CONSTRAINT REVENUE_ITEMS_CHK4 CHECK 
(QUANTITY >=0)
ENABLE;

ALTER TABLE REVENUE_ITEMS
ADD CONSTRAINT REVENUE_ITEMS_CHK5 CHECK 
(SETTLED_PRICE >0)
ENABLE;

ALTER TABLE SALES_TEAMS
ADD CONSTRAINT SALES_TEAMS_CHK1 CHECK 
(LENGTH(TEAM_NAME) BETWEEN 1 AND 20)
ENABLE;

ALTER TABLE TASK
ADD CONSTRAINT TASK_CHK1 CHECK 
(TASK_START_DATE < DUE_DATE)
ENABLE;

ALTER TABLE TASK
ADD CONSTRAINT TASK_CHK2 CHECK 
(TASK_COMPLETION >=0 AND TASK_COMPLETION <= 100)
ENABLE;

ALTER TABLE USERS
ADD CONSTRAINT USERS_CHK1 CHECK 
(START_DATE < END_DATE)
ENABLE;

CREATE SEQUENCE ADDRSEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE APPOINTSEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CONSEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CONTSEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CUSTSEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE INTERSEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE NOTESEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE OPPORSEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE PRODSEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 100 CACHE 20;

CREATE SEQUENCE ROLESEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE TASKSEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE USERACCSEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE TRIGGER ADDRTR 
BEFORE INSERT ON ADDRESS 
FOR EACH ROW 
WHEN (NEW.ADDRESS_ID IS NULL) 
BEGIN
  SELECT ADDRSEQ.NEXTVAL
  INTO :NEW.ADDRESS_ID
  FROM DUAL;
END;
/

CREATE TRIGGER APPOTR 
BEFORE INSERT ON APPOINTMENTS 
FOR EACH ROW 
WHEN (new.APPOINTMENT_ID IS NULL) 
BEGIN
  SELECT APPOINTSEQ.NEXTVAL
  INTO :new.APPOINTMENT_ID 
  FROM DUAL;
END;
/

CREATE TRIGGER CONTR 
BEFORE INSERT ON CONTRACTS 
FOR EACH ROW 
WHEN (new.CONTRACT_ID IS NULL) 
BEGIN
  SELECT CONSEQ.NEXTVAL
  INTO :new.CONTRACT_ID 
  FROM DUAL;
END;
/

CREATE TRIGGER CONTTR 
BEFORE INSERT ON CONTACTS 
FOR EACH ROW 
WHEN (new.CONTACT_ID IS NULL) 
BEGIN
  NULL;
END;
/

CREATE TRIGGER CUSTOMERACCOUNTTR 
BEFORE INSERT ON CUSTOMER_ACCOUNTS 
FOR EACH ROW 
WHEN (new.ACCOUNT_ID IS NULL) 
BEGIN
  SELECT CUSTSEQ.NEXTVAL
  INTO :new.ACCOUNT_ID
  FROM Dual;
END;
/

CREATE TRIGGER INTERTR 
BEFORE INSERT ON INTERACTIONS 
FOR EACH ROW 
WHEN (new.ID IS NULL) 
BEGIN
  SELECT INTERSEQ.nextval
  INTO :new.ID
  FROM dual;
END;
/

CREATE TRIGGER NOTETR 
BEFORE INSERT ON NOTES 
FOR EACH ROW 
WHEN (new.NOTE_ID IS NULL) 
BEGIN
  SELECT NOTESEQ.nextval
  INTO :new.NOTE_ID
  FROM DUAL;
END;
/

CREATE TRIGGER OPPORTR 
BEFORE INSERT ON OPPORTUNITY 
FOR EACH ROW 
WHEN (new.ID IS NULL) 
BEGIN
  SELECT OPPORSEQ.NEXTVAL
  INTO :new.ID 
  FROM DUAL;
END;
/

CREATE TRIGGER PRODTR 
BEFORE INSERT ON PRODUCTS 
FOR EACH ROW 
WHEN (new.PRODUCT_CODE IS NULL) 
BEGIN
  SELECT PRODSEQ.NEXTVAL
  INTO :new.PRODUCT_CODE 
  FROM DUAL;
END;
/

CREATE TRIGGER ROLETR 
BEFORE INSERT ON ROLES_TABLE 
FOR EACH ROW 
WHEN (new.ID IS NULL) 
BEGIN
  SELECT ROLESEQ.NEXTVAL
  INTO :new.ID 
  FROM DUAL;
END;
/

CREATE TRIGGER TASKTR 
BEFORE INSERT ON TASK 
FOR EACH ROW 
WHEN (new.TASK_ID IS NULL) 
BEGIN
  SELECT TASKSEQ.NEXTVAL
  INTO :new.TASK_ID 
  FROM DUAL;
END;
/

CREATE TRIGGER USERACCTR 
BEFORE INSERT ON USERS 
FOR EACH ROW 
WHEN (new.USER_ID IS NULL) 
BEGIN
  SELECT USERACCSEQ.NEXTVAL
  INTO :new.USER_ID 
  FROM DUAL;
END;
/
