package model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 16 17:07:20 IST 2017
// ---------------------------------------------------------------------
public interface AppModuleAM extends ApplicationModule {
    void UpdateUser();
}

