package model.UVO;

import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 17 14:11:56 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AssignTeamUVORowImpl extends ViewRowImpl {
    public static final int ENTITY_SALESTEAMSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ManagerId,
        TeamId,
        TeamName,
        ManagerUVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int TEAMID = AttributesEnum.TeamId.index();
    public static final int TEAMNAME = AttributesEnum.TeamName.index();
    public static final int MANAGERUVO1 = AttributesEnum.ManagerUVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AssignTeamUVORowImpl() {
    }

    /**
     * Gets SalesTeamsEO entity object.
     * @return the SalesTeamsEO
     */
    public EntityImpl getSalesTeamsEO() {
        return (EntityImpl) getEntity(ENTITY_SALESTEAMSEO);
    }

    /**
     * Gets the attribute value for MANAGER_ID using the alias name ManagerId.
     * @return the MANAGER_ID
     */
    public Long getManagerId() {
        return (Long) getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MANAGER_ID using the alias name ManagerId.
     * @param value value to set the MANAGER_ID
     */
   

    /**
     * Gets the attribute value for TEAM_ID using the alias name TeamId.
     * @return the TEAM_ID
     */
    public Long getTeamId() {
        return (Long) getAttributeInternal(TEAMID);
    }

    /**
     * Sets <code>value</code> as attribute value for TEAM_ID using the alias name TeamId.
     * @param value value to set the TEAM_ID
     */
    public void setTeamId(Long value) {
        setAttributeInternal(TEAMID, value);
    }

    /**
     * Gets the attribute value for TEAM_NAME using the alias name TeamName.
     * @return the TEAM_NAME
     */
    public String getTeamName() {
        return (String) getAttributeInternal(TEAMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TEAM_NAME using the alias name TeamName.
     * @param value value to set the TEAM_NAME
     */
    public void setTeamName(String value) {
        setAttributeInternal(TEAMNAME, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ManagerUVO1.
     */
    public RowSet getManagerUVO1() {
        return (RowSet) getAttributeInternal(MANAGERUVO1);
    }
    
    public void setManagerId(Long value) {
     
        setAttributeInternal(MANAGERID, value);
        
    }
}

